sudo: false
dist: trusty
language: node_js

cache: apt

addons:
  firefox: "51.0"


before_install:
    - if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi

install:
    - npm install -g web-ext

script: web-ext build && mv web-ext-artifacts/*.zip extension.zip

deploy:
    provider: releases
    api_key: "${GH_TOKEN}"
    file: "extension.zip"
    skip_cleanup: true
    on:
        tags: true

user:12557732:593
c01254fd924abdd447b821d7d002eb39782b6aac25506bdc89c992fe9e4e9b4a
